# Generated by Django 4.2.7 on 2023-11-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='address',
        ),
        migrations.RemoveField(
            model_name='food',
            name='tg_username',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
